Repository hdm-chat-team/application-project-ws24, pull requests merged in 2024-11, with the labels that each got.

#7 chore: 🎨 improve backend structure
  README.md
  apps/backend/package.json
  apps/backend/src/app.test.ts
  apps/backend/src/app.ts
  apps/backend/src/client.ts
  apps/backend/src/index.ts
  apps/backend/src/lib/types.ts
  apps/backend/src/routes/chat/index.ts
  apps/backend/src/routes/rest/index.ts
  apps/frontend/package.json
  apps/frontend/src/lib/api.ts
  apps/frontend/src/routes/index.lazy.tsx
  biome.json
  bun.lockb
  yarn.lock
Labels: documentation, enhancement

#12 11 shadcn
  apps/frontend/components.json
  apps/frontend/package.json
  apps/frontend/src/components/theme-provider.tsx
  apps/frontend/src/components/ui/button.tsx
  apps/frontend/src/lib/utils.ts
  apps/frontend/src/main.css
  apps/frontend/src/routes/__root.tsx
  apps/frontend/src/routes/index.lazy.tsx
  apps/frontend/tailwind.config.ts
  biome.json
  bun.lockb
  yarn.lock
Labels: enhancement

#13 8 implement local database
  apps/frontend/package.json
  apps/frontend/src/components/message-input.tsx
  apps/frontend/src/lib/hooks/use-message-service.ts
  apps/frontend/src/lib/message-service.ts
  apps/frontend/src/routes/test-page.lazy.tsx
  bun.lockb
  yarn.lock
Labels: enhancement

#15 fix(backend): 🚚restructure app
  .git-blame-ignore-revs
  .gitignore
  README.md
  app/.env
  app/Dockerfile
  app/backend/app.test.ts
  app/backend/app.ts
  app/backend/client.ts
  app/backend/index.ts
  app/backend/lib/config.ts
  app/backend/lib/factory.ts
  app/backend/lib/middleware.ts
  app/backend/lib/types.ts
  app/backend/routes/chat/index.test.ts
  app/backend/routes/chat/index.ts
  app/frontend/components.json
  app/frontend/index.html
  app/frontend/package.json
  app/frontend/postcss.config.js
  app/frontend/public/apple-touch-icon-180x180.png
  app/frontend/public/favicon.ico
  app/frontend/public/logo.svg
  app/frontend/public/maskable-icon-512x512.png
  app/frontend/public/pwa-192x192.png
  app/frontend/public/pwa-512x512.png
  app/frontend/public/pwa-64x64.png
  app/frontend/src/assets/react.svg
  app/frontend/src/components/message-input.tsx
  app/frontend/src/components/theme-provider.tsx
  app/frontend/src/components/ui/button.tsx
  app/frontend/src/hooks/use-message-service.ts
  app/frontend/src/lib/api.ts
  app/frontend/src/lib/message-service.ts
  app/frontend/src/lib/utils.ts
  app/frontend/src/main.css
  app/frontend/src/main.tsx
  app/frontend/src/routes/__root.tsx
  app/frontend/src/routes/index.lazy.tsx
  app/frontend/src/routes/test-page.lazy.tsx
  app/frontend/src/vite-env.d.ts
  app/frontend/tailwind.config.ts
  app/frontend/tsconfig.json
  app/frontend/vite.config.ts
  app/package.json
  app/tsconfig.json
  apps/backend/package.json
  apps/backend/src/app.test.ts
  apps/backend/src/app.ts
  apps/backend/src/client.ts
  apps/backend/src/lib/middleware.ts
  apps/frontend/src/components/ui/button.tsx
  apps/frontend/src/lib/api.ts
  biome.json
  bun.lockb
  docker-compose.yml
  package.json
  packages/database/package.json
  turbo.json
  yarn.lock
Labels: bug, enhancement

#10 1 GitHub oauth
  .dockerignore
  .github/workflows/test.yml
  .gitignore
  app/.env
  app/.env.example
  app/backend/app.test.ts
  app/backend/app.ts
  app/backend/auth/oauth.ts
  app/backend/auth/session.ts
  app/backend/client.ts
  app/backend/db/db.ts
  app/backend/db/queries.sql.ts
  app/backend/db/schema.sql.ts
  app/backend/lib/config.ts
  app/backend/lib/factory.ts
  app/backend/lib/middleware.ts
  app/backend/lib/types.ts
  app/backend/routes/auth/github.ts
  app/backend/routes/auth/index.ts
  app/backend/routes/chat.test.ts
  app/backend/routes/chat.ts
  app/drizzle.config.ts
  app/frontend/package.json
  app/frontend/src/components/message-input.tsx
  app/frontend/src/lib/api.ts
  app/frontend/src/routes/index.lazy.tsx
  app/frontend/src/routes/login/index.tsx
  app/frontend/vite.config.ts
  app/package.json
  bun.lockb
  package.json
  packages/database/.env
  packages/database/package.json
  packages/database/src/schema.sql.ts
  packages/database/tsconfig.json
  yarn.lock
Labels: enhancement

#20 18 runtime typechecking
  .github/workflows/test.yml
  app/backend/app.ts
  app/backend/auth/oauth.ts
  app/backend/db/db.ts
  app/backend/db/schema.sql.ts
  app/backend/index.ts
  app/backend/lib/cookie.ts
  app/backend/lib/factory.ts
  app/backend/lib/middleware.ts
  app/backend/routes/auth/github.ts
  app/backend/routes/auth/github/index.schemas.ts
  app/backend/routes/auth/github/index.ts
  app/backend/routes/chat.test.ts
  app/backend/routes/chat.ts
  app/drizzle.config.ts
  app/env.ts
  app/frontend/package.json
  app/frontend/src/routes/__root.tsx
  app/package.json
  bun.lockb
  yarn.lock
Labels: enhancement
