Repository hdm-chat-team/application-project-ws24, pull requests merged in 2024-12, with the labels that each got.

#27 21 continuous deployement
  .dockerignore
  Dockerfile
  README.md
  app/Dockerfile
  app/backend/app.test.ts
  app/backend/app.ts
  app/backend/auth/session.test.ts
  app/backend/lib/cookie.ts
  app/backend/lib/factory.test.ts
  app/backend/lib/factory.ts
  app/backend/lib/middleware.test.ts
  app/backend/routes/auth/github/index.ts
  app/backend/routes/auth/index.test.ts
  app/backend/routes/auth/index.ts
  app/env.test.ts
  app/env.ts
  app/frontend/package.json
  app/frontend/src/lib/api.ts
  app/package.json
  bun.lockb
  bunfig.toml
  docker-compose.yml
  package.json
  yarn.lock
Labels: enhancement, CI/CD

#22 feat: Signin page
  app/frontend/package.json
  app/frontend/src/assets/hdm-logo-clipart-lg.png
  app/frontend/src/components/mode-toggle.tsx
  app/frontend/src/components/sidebar/index.tsx
  app/frontend/src/components/ui/card.tsx
  app/frontend/src/components/ui/dropdown-menu.tsx
  app/frontend/src/components/ui/input.tsx
  app/frontend/src/routes/index.lazy.tsx
  app/frontend/src/routes/login/index.tsx
  app/frontend/src/routes/signin/index.tsx
  package.json
Labels: enhancement

#29 28 rate limiting
  app/backend/app.test.ts
  app/backend/lib/cookie.ts
  app/backend/lib/factory.test.ts
  app/backend/lib/factory.ts
  app/backend/lib/middleware.test.ts
  app/backend/lib/middleware.ts
  app/backend/routes/auth/github/index.ts
  app/backend/routes/auth/index.test.ts
  app/backend/routes/auth/index.ts
  app/env.ts
  app/frontend/package.json
  app/frontend/src/components/sidebar/index.tsx
  app/frontend/src/main.tsx
  app/frontend/src/routes/__root.tsx
  app/frontend/src/routes/index.lazy.tsx
  app/package.json
  bun.lockb
  package.json
Labels: enhancement

#31 16 message storage logic with websocket integration
  app/backend/routes/auth/index.ts
  app/frontend/src/hooks/use-message-service.ts
  app/frontend/src/lib/auth-context.ts
  app/frontend/src/lib/auth-provider.tsx
  app/frontend/src/lib/message-service.ts
  app/frontend/src/main.tsx
  app/frontend/src/routes/index.lazy.tsx
  app/frontend/src/routes/test-page.lazy.tsx
  package.json
Labels: enhancement

#37 36 authenticated routes
  app/backend/routes/auth/github.schemas.ts
  app/backend/routes/auth/github.ts
  app/frontend/src/features/auth/components/github-signin-button.tsx
  app/frontend/src/features/auth/index.ts
  app/frontend/src/routes/(app)/_authenticated.tsx
  app/frontend/src/routes/(app)/_authenticated/index.lazy.tsx
  app/frontend/src/routes/(auth)/signin.tsx
  app/frontend/src/routes/(wip)/test-page.lazy.tsx
Labels: enhancement

#44 36 authenticated routes
  app/backend/db/schema.sql.ts
  app/backend/lib/factory.ts
  app/backend/lib/middleware.test.ts
  app/backend/lib/middleware.ts
  app/backend/routes/auth/github.schemas.ts
  app/backend/routes/auth/github.test.ts
  app/backend/routes/auth/github.ts
  app/backend/routes/auth/index.schemas.ts
  app/backend/routes/auth/index.test.ts
  app/backend/routes/auth/index.ts
  app/frontend/package.json
  app/frontend/src/components/mode-toggle.tsx
  app/frontend/src/components/ui/card.tsx
  app/frontend/src/components/ui/dropdown-menu.tsx
  app/frontend/src/components/ui/input.tsx
  app/frontend/src/context/index.ts
  app/frontend/src/context/theme-provider.tsx
  app/frontend/src/features/auth/components/github-signin-button.tsx
  app/frontend/src/features/auth/components/signout-button.tsx
  app/frontend/src/features/auth/context/auth-provider.tsx
  app/frontend/src/hooks/index.ts
  app/frontend/src/hooks/use-theme.ts
  app/frontend/src/main.css
  app/frontend/src/main.tsx
  app/frontend/src/routes/(app)/_authenticated.tsx
  app/frontend/src/routes/(app)/_authenticated/index.lazy.tsx
  app/frontend/src/routes/(auth)/signin.tsx
  app/frontend/src/routes/__root.tsx
  app/package.json
  biome.json
  bun.lockb
  package.json
  packages/tsconfig/package.json
  turbo.json
Labels: enhancement

#43 32 endpoints for profile management
  app/backend/app.ts
  app/backend/routes/user/profiles.test.ts
  app/backend/routes/user/profiles.ts
  bun.lockb
Labels: enhancement

#53 build(frontend): ⬆️ upgrade dependencies
  app/frontend/package.json
  bun.lockb
Labels: CI/CD

#58 57 use domain in prod
  .gitignore
  app/backend/api/app.env.ts
  app/backend/api/auth/github.ts
  app/backend/api/factory.ts
  app/backend/lib/middleware.ts
  app/drizzle.config.ts
  app/env.ts
  app/frontend/src/features/chat/components/message-form.tsx
  app/frontend/src/features/chat/hooks/index.ts
  app/frontend/src/features/chat/hooks/use-chat.tsx
  app/frontend/src/features/chat/hooks/use-post-message.tsx
  app/frontend/src/features/chat/hooks/use-save-message.tsx
  app/frontend/src/features/chat/queries.ts
  app/frontend/src/features/db/queries.ts
  app/frontend/src/routes/(app)/_authenticated/chat.$id.tsx
  app/package.json
  biome.json
  bun.lockb
  drizzle/0000_absurd_alice.sql
  drizzle/meta/0000_snapshot.json
  drizzle/meta/_journal.json
Labels: bug
