Repository hdm-chat-team/application-project-ws24, pull requests merged in 2025-02, with the labels that each got.

#89 chore: add dependabot.yml
  .github/dependabot.yml
Labels: CI/CD

#88 87 add seeding
  app/backend/db/scripts/seed.ts
  app/package.json
  bun.lock
Labels: enhancement

#106 fix(auth): 🐛 infinite loop
  app/frontend/src/features/auth/queries.ts
  app/frontend/src/routes/(auth)/signin.tsx
Labels: bug

#100 99 add attachment preview
  app/backend/api/chat/index.ts
  app/backend/db/messages.sql.ts
  app/backend/db/messages.ts
  app/frontend/src/features/message/components/message-attachment.tsx
  app/frontend/src/features/message/components/message-form.tsx
  app/frontend/src/features/message/hooks/use-mutations.tsx
  app/frontend/src/features/message/utils.ts
  app/frontend/src/features/uploadthing/components/caption-input.tsx
  app/frontend/src/features/uploadthing/components/file-button.tsx
  app/frontend/src/features/uploadthing/components/file-picker.tsx
  app/frontend/src/features/uploadthing/components/file-preview.tsx
  app/frontend/src/routes/_app/attachment.tsx
  app/shared/types.ts
Labels: enhancement

#111 107 from url to customid storage
  app/backend/api/uploadthing/index.ts
  app/frontend/src/features/message/components/index.tsx
  app/frontend/src/features/message/components/message-attachment.tsx
  app/frontend/src/features/message/hooks/use-mutations.tsx
  app/frontend/src/features/message/utils.ts
  app/frontend/src/features/profile/components/avatar-uploader.tsx
  app/frontend/src/features/profile/hooks/use-upload-avatar.tsx
  app/frontend/src/features/uploadthing/mutations.ts
  app/frontend/src/features/uploadthing/types.ts
  app/frontend/src/features/uploadthing/utils.ts
  app/frontend/src/hooks/socket/use-ws-events.tsx
  app/frontend/src/lib/db.ts
  app/frontend/src/routes/_app/attachment.tsx
  app/shared/types.ts
  bun.lock
Labels: enhancement

#110 109 datechip
  app/frontend/src/components/nav/top-nav.tsx
  app/frontend/src/features/chat/components/header.tsx
  app/frontend/src/features/chat/components/index.tsx
  app/frontend/src/main.css
  app/frontend/src/routes/(auth)/signin.tsx
  app/frontend/src/routes/_app.tsx
  app/frontend/src/routes/_app/index.tsx
  app/frontend/src/routes/_app/new/index.tsx
  app/frontend/src/routes/_app/user.tsx
Labels: bug, enhancement
